# Generated by Django 5.2 on 2026-06-15 06:56
#
# Adds UsageCostLog (one row per billable provider call) and ChatSession.total_cost
# (denormalised running total that avoids aggregating UsageCostLog on every dashboard request).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0081_alter_chatsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='UsageCostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('LLM', 'LLM'), ('TTS', 'Text To Speech'), ('STT', 'Speech To Text'), ('TRANSLATE', 'Translation'), ('TRANSLITERATE', 'Transliteration')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('input_units', models.IntegerField(default=0)),
                ('output_units', models.IntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('other_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.companybot')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.profile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_cost_logs', to='chatbot.chatsession')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='chatbot_usa_created_4824a8_idx')],
            },
        ),
    ]
